export const copy = {
  en: {
    app: {
      startupIssue: 'Startup issue',
      startupTitle: 'The story app could not load.',
      loadingStory: 'Loading the story',
      loadingTitle: 'Preparing the project walkthrough.',
      loadingDescription:
        'The app is loading real research notes, real model outputs, and real dataset slices from the local radiative-cooling project.',
      contentLoadError: 'The app content could not be loaded. Run npm run sync-content and try again.',
      unknownStartupError: 'Unknown startup error',
      loadingRoute: 'Loading route',
      routeDescription:
        'This route is split from the startup bundle so the story app can stay fast while still loading the heavier research and charting views on demand.',
      routeLabels: {
        story: 'story',
        pipeline: 'pipeline',
        comparison: 'comparison',
        explorer: 'explorer',
        notebook: 'lab notebook',
        research: 'research library',
        audit: 'audit',
      },
      preparingRoute: (label: string) => `Preparing the ${label} view.`,
    },
    shell: {
      appName: 'RCML App',
      nav: {
        story: {
          label: 'Story',
          eyebrow: 'Overview',
          detail: 'High-level summary, verdict, and navigation into the evidence.',
        },
        pipeline: {
          label: 'Pipeline',
          eyebrow: 'Workflow',
          detail: 'Step-by-step path from dataset generation to verification.',
        },
        compare: {
          label: 'Compare',
          eyebrow: 'Models',
          detail: 'Head-to-head model behavior and retained workflow logic.',
        },
        explore: {
          label: 'Explore',
          eyebrow: 'Structures',
          detail: 'Candidate stacks, spectra, and target-by-target inspection.',
        },
        notebook: {
          label: 'Notebook',
          eyebrow: 'Code',
          detail: 'Real commands, source files, metrics, and artifact panels.',
        },
        research: {
          label: 'Research',
          eyebrow: 'Sources',
          detail: 'Internal guides plus the actual external papers reviewed.',
        },
        audit: {
          label: 'Audit',
          eyebrow: 'Evidence',
          detail: 'Timeline, files of record, and final audit checkpoints.',
        },
      },
      evidenceLoaded: 'Evidence loaded',
      guides: 'Guides',
      papers: 'Papers',
      oaPdfs: 'OA PDFs',
      shellIntent: 'Shell intent',
      shellIntentBody:
        'This is meant to behave like an inspectable workbench: navigation on the left, dense evidence in the inset, and a single content pane that scrolls independently.',
      openAccessResolved: (count: number) => `${count} open-access sources resolved`,
      realEvidence: 'Real local notes, artifacts, and code',
    },
    controls: {
      toggleTheme: 'Toggle color theme',
      switchToDark: 'Switch to dark mode',
      switchToLight: 'Switch to light mode',
      darkMode: 'Dark mode',
      lightMode: 'Light mode',
      toggleLanguage: 'Toggle language',
      switchToChinese: 'Switch to Simplified Chinese',
      switchToEnglish: 'Switch to English',
      english: 'English',
      chinese: '简体中文',
      englishShort: 'EN',
      chineseShort: '简中',
    },
    common: {
      open: 'Open',
      hide: 'Hide',
      noEvidence: 'No evidence files available.',
      fileCount: (count: number) => `${count} file${count === 1 ? '' : 's'}`,
      layer: (index: number) => `Layer ${index}`,
      sourceFile: (path: string) => `Source file: ${path}`,
      source: (path: string) => `Source: ${path}`,
      sample: (sampleId: string) => `sample: ${sampleId}`,
      totalThickness: (value: string) => `total thickness: ${value} nm`,
      verifiedTotalError: 'verified total error',
      commands: 'Commands',
      files: 'Files',
      metrics: 'Metrics',
      evidence: 'Evidence',
      records: 'Records',
      timeline: 'Timeline',
      currentStage: 'Current stage',
      selected: 'Selected',
      openPanels: 'Open panels',
      notResolved: 'Not resolved',
      unknown: 'Unknown',
      yearUnknown: 'Year unknown',
      venueUnresolved: 'Venue unresolved',
      currentSelectedStage: 'Current selected stage',
      reflectorAt: (material: string, value: string) => `${material} reflector at ${value} nm`,
    },
    enums: {
      modelStatus: {
        baseline: 'baseline',
        retained: 'retained',
        competitive: 'competitive',
        rejected: 'rejected',
      },
      paperStatus: {
        downloaded: 'Local PDF ready',
        'open-access-link': 'Source link only',
        'citation-only': 'Citation only',
      },
      paperCategory: {
        core: 'Core paper',
        foundation: 'Method foundation',
        recent: 'Recent follow-up',
      },
      panelKind: {
        artifact: 'artifact',
        code: 'code',
      },
      candidateFamily: {
        tandem: 'tandem',
        diffusion: 'diffusion',
        'continuous-cvae': 'continuous CVAE',
        'categorical-cvae': 'categorical CVAE',
      },
      candidateRoute: {
        shortlist: 'shortlist',
        'raw-best-of-64': 'raw best-of-64',
        'single-proposal': 'single proposal',
      },
    },
    home: {
      heroEyebrow: 'The whole story, not just the verdict',
      heroTitle: 'Follow what was trained, what it meant, and why one workflow survived the audit.',
      walkPipeline: 'Walk the pipeline',
      openNotebook: 'Open the lab notebook',
      compareModels: 'Compare the models',
      readResearch: 'Read the research library',
      projectMode: 'Project mode',
      projectModeTitle: 'Evidence-first workbench',
      projectModeDescription: 'Narrative, code, papers, and verification live in one app frame.',
      dataset: 'Dataset',
      datasetDescription: 'Real spectra and real multilayer stacks, not summary placeholders.',
      research: 'Research',
      researchDescription: 'Open-access PDFs are local only when the source legitimately allows it.',
      retainedWorkflow: 'Retained workflow',
      defaultPath: 'Default path',
      visualFirst: 'Visual first',
      visualTitle: 'Use the notebook if you want the actual repo guts',
      visualDescription:
        'That route shows the real CLI entrypoints, real commands, real metric files, and the shortlist verification JSON in Monaco panels.',
      goToNotebook: 'Go to notebook',
      seePhysics: 'See the physics',
      seePhysicsTitle: 'Use Explore when you need to see actual spectra and stacks',
      seePhysicsDescription:
        'That page is where the dataset and candidate structures stop being names and start looking like curves, layers, and verified metric tables.',
      openExplore: 'Open Explore',
      sourceTrail: 'Source trail',
      sourceTrailTitle: 'Use Research when you want the notes and bibliography',
      sourceTrailDescription:
        'The guides explain what we wrote. The paper library shows what external literature we actually reviewed, with local open-access PDFs only when they are legitimately available.',
      openResearch: 'Open Research',
      sectionEyebrow: 'What this app helps with',
      sectionTitle: 'A denser way to navigate the project',
      sectionDescription:
        'The goal is to make the project legible without flattening it into a marketing page. Each section points back to the actual local evidence while still explaining what happened in plain language.',
      chapter: (index: number) => `Chapter ${index}`,
      twoReferenceWins: 'Two reference wins',
      whatHappenedOverTime: 'What happened over time',
    },
    pipeline: {
      eyebrow: 'Pipeline and data flow',
      title: 'The project is a chain of decisions, not one model button',
      description:
        'This section shows what went in, what came out, and why each stage existed. The important idea is that the final answer came from a loop: define a legal design space, generate real data, train fast approximations, sample candidates, and then go back to the simulator for the final check.',
      designSpace: 'Design space',
      thicknessBounds: 'Thickness bounds',
      thicknessDescription: 'Each dielectric layer must stay in this range.',
      spectralGrid: 'Spectral grid',
      spectralDescription: (start: string, stop: string) => `${start} to ${stop} μm per spectrum.`,
      keyBands: 'Key bands',
      keyBandsDescription: 'Solar band and 8-13 μm atmospheric window drive the story.',
      visualStageMap: 'Visual stage map',
      visualTitle: 'The pipeline is easier to follow when each stage is a box you can inspect',
      visualDescription:
        'These are the same stages exposed in the notebook route, where each one opens into Monaco code panels, real commands, and artifact outputs.',
      openNotebook: 'Open lab notebook',
      inputs: 'Inputs',
      outputs: 'Outputs',
      glossary: 'Plain-language glossary',
      loopMatters: 'Why the loop matters',
      loopTitle: 'A training run was never treated as the final truth.',
      loopDescription:
        'The strongest idea in the project is procedural rather than decorative: sample broadly, score quickly, and then return to the simulator before calling a design good. That is why the final result is more trustworthy than a single model metric.',
      stepLabel: (index: number, eyebrow: string) => `${index}. ${eyebrow}`,
    },
    compare: {
      eyebrow: 'Model comparison',
      title: 'The winning workflow was earned by verification, not by confidence',
      description:
        'The comparison page focuses on how each model family behaved when it was pushed through the same evidence loop. Metrics matter, but the real decision came from verified target error after the shortlist and simulator checks.',
      retainedBestMethod: 'Retained best method',
      inspectNotebook: 'Inspect the run notebook',
      seeWinningStructures: 'See winning structures',
      split: 'split',
      device: 'device',
      verifiedHighlights: 'Verified highlights',
      targetTitle: 'What happened on this target',
    },
    explore: {
      eyebrow: 'Data and candidate explorer',
      title: 'Real spectra and real verified stacks',
      description:
        'This viewer separates two different kinds of evidence. First, you can inspect real samples from the 4096-record training corpus and see their spectra directly. Second, you can inspect curated verified candidates that emerged from the model-comparison story.',
      datasetSamplePicker: 'Real dataset sample picker',
      candidatePicker: 'Verified candidate picker',
      realSpectrumViewer: 'Real spectrum viewer',
      verifiedCandidate: 'Verified candidate',
      targetMetrics: 'Target metrics',
      simulatorMetrics: 'Simulator-confirmed metrics',
      absoluteError: 'Absolute error by metric',
      reflectance: 'Reflectance',
      emissivity: 'Emissivity',
    },
    notebook: {
      eyebrow: 'Lab notebook',
      title: 'The actual code, commands, and artifact files behind the story',
      stageCount: (count: number) => `${count} notebook stages`,
      commandCount: (count: number) => `${count} real commands`,
      panelCount: (count: number) => `${count} code and artifact panels`,
      currentStageBadge: (eyebrow: string) => `Current stage: ${eyebrow}`,
      stageCardDescription: 'From config and dataset generation through shortlist verification and audit.',
      commandCardDescription: 'Reproduction commands and command patterns used by the current repo.',
      panelCardDescription: 'Monaco tabs let you inspect source files, metric bundles, and verification JSON directly.',
      workspaceTabs: {
        files: 'Code and artifacts',
        commands: 'Terminal commands',
        overview: 'Stage notes',
      },
      noPanels: 'No code or artifact panels are available for this stage.',
      whatHappenedHere: 'What happened here',
      whyItMatters: 'Why it matters',
    },
    research: {
      eyebrow: 'Research library',
      title: 'Internal guides on one side, actual external papers on the other',
      description:
        'This page now separates two different kinds of evidence. The guides are the local markdown notes we wrote for this project. The papers are the external sources we reviewed, with official links and local open-access PDFs only when a legitimate OA copy could be resolved.',
      internalGuides: 'Internal guides',
      papersReviewed: 'Papers reviewed',
      localPdfs: 'Local OA PDFs',
      resolvedLinks: 'Resolved OA links',
      internalGuidesDescription: 'Local markdown walkthroughs and audits written during this project.',
      papersDescription: 'Papers resolved from the local bibliography and literature notes.',
      localPdfsDescription: 'Downloaded only when an official open-access PDF was discoverable.',
      resolvedLinksDescription: 'The number of references where OpenAlex found an open-access source URL.',
      searchLabel: 'Search across guides and papers',
      searchPlaceholder: "Try 'diffusion', 'Bayesian', or 'Keawmuang'",
      paperLibrary: 'Paper library',
      guideLibrary: 'Guide library',
      paperVisibleCount: (visible: number, total: number) => `${visible} of ${total} papers visible.`,
      guideVisibleCount: (visible: number, total: number) => `${visible} of ${total} guides visible.`,
      guideShelf: 'Guide shelf',
      paperShelf: 'Paper shelf',
      internalProjectGuide: 'Internal project guide',
      authors: 'Authors',
      venue: 'Venue',
      year: 'Year',
      citations: 'Citations',
      overview: 'Overview',
      details: 'Details',
      pdf: 'PDF',
      openOfficialSource: 'Open official source',
      openLocalPdf: 'Open local PDF',
      localPdfSize: (size: string) => `Local PDF size: ${size}`,
      externalPdfFound: 'An open-access source URL was found, but no local PDF was downloaded.',
      noLocalPdf: 'No local PDF is available for this reference in the current workspace.',
      embeddedLocalPdf: 'Embedded local PDF',
      embeddedPdfNote: 'The library keeps the PDF in view while the shelf and metadata stay anchored.',
      standaloneView: 'Standalone view',
      browserDidNotRender: 'The browser did not render the embedded PDF inline.',
      openPdfNewTab: 'Open local PDF in a new tab',
      referenceDetails: 'Reference details',
      doi: 'DOI',
      officialLink: 'Official link',
      openAccessPdfUrl: 'Open-access PDF URL',
      projectNote: 'Project note',
      availability: 'Availability',
      availabilityLocal: 'A local PDF is present in the workspace and can be opened in the PDF tab.',
      availabilityExternal: 'An external PDF link was resolved, but the generator did not persist a local copy.',
      availabilityNone: 'Only the citation and official source are available right now.',
      sourceNote: 'Source note',
      whyPaperMattered: 'Why this paper mattered in the project',
      pdfAvailabilityRule: 'PDF availability rule',
      pdfAvailabilityRuleBody:
        'The app only stores a local PDF when an official open-access PDF URL can be resolved. If a paper is not open access, the app keeps the citation and official source link without rehosting the paper itself.',
      noGuides: 'No guides matched the current search.',
      noPapers: 'No papers matched the current search.',
    },
    audit: {
      eyebrow: 'Final audit',
      title: 'The end result stayed conservative because the evidence stayed conservative',
      description:
        'The audit was not just a summary pass. It checked the dataset, the training environment, and the most plausible remaining modeling issue. The final verdict was to keep the continuous-CVAE shortlist workflow because the audited categorical branch did not beat it under full verification.',
      checkpointCount: (count: number) => `${count} audit checkpoints`,
      recordCount: (count: number) => `${count} files of record`,
      selectedCheckpointBadge: (title: string) => `Selected checkpoint: ${title}`,
      auditVerdict: 'Audit verdict',
      auditVerdictTitle: 'Keep the continuous-decoder CVAE as the default.',
      auditVerdictDescription:
        'The categorical-material decoder addressed a real modeling mismatch, but it still failed to beat the retained workflow after the same shortlist-plus-physics loop.',
      auditTimeline: 'Audit timeline',
      selectedCheckpoint: 'Selected checkpoint',
      workspaceTabs: {
        evidence: 'Checkpoint evidence',
        records: 'Files of record',
        verdict: 'Audit verdict',
      },
      checkpoint: (index: number) => `Checkpoint ${index}`,
      verdict: 'Verdict',
      checkpointSummaries: 'Checkpoint summaries',
      datasetSize: 'Dataset size',
      datasetSizeDetail: 'Real WPTherml records in the final training corpus.',
      wavelengthGrid: 'Wavelength grid',
      wavelengthGridDetail: 'Each reflectance and emissivity spectrum uses this many real wavelength points.',
      retainedWinner: 'Retained winner',
      retainedWinnerDetail: 'Best curated verified error shown in the final report.',
      categoricalBranch: 'Categorical branch',
      categoricalBranchDetail: 'Sample255 raw error from the rejected categorical audit branch.',
    },
  },
  'zh-Hans': {
    app: {
      startupIssue: '启动问题',
      startupTitle: '故事应用无法加载。',
      loadingStory: '正在加载内容',
      loadingTitle: '正在准备项目导览。',
      loadingDescription: '应用正在从本地辐射制冷项目中加载真实研究笔记、真实模型输出和真实数据切片。',
      contentLoadError: '应用内容无法加载。请先运行 npm run sync-content，然后重试。',
      unknownStartupError: '未知启动错误',
      loadingRoute: '正在加载路由',
      routeDescription: '这个路由从启动包中拆分出来，以便应用在保持启动速度的同时，按需加载更重的研究与图表视图。',
      routeLabels: {
        story: '总览',
        pipeline: '流程',
        comparison: '比较',
        explorer: '探索',
        notebook: '实验笔记',
        research: '研究资料库',
        audit: '审计',
      },
      preparingRoute: (label: string) => `正在准备${label}视图。`,
    },
    shell: {
      appName: 'RCML 应用',
      nav: {
        story: {
          label: '总览',
          eyebrow: '概览',
          detail: '高层摘要、最终结论，以及进入证据的导航入口。',
        },
        pipeline: {
          label: '流程',
          eyebrow: '工作流',
          detail: '从数据集生成到最终验证的逐步路径。',
        },
        compare: {
          label: '比较',
          eyebrow: '模型',
          detail: '各模型的正面对比，以及保留工作流的判断依据。',
        },
        explore: {
          label: '探索',
          eyebrow: '结构',
          detail: '查看候选层堆、光谱，以及逐目标检查。',
        },
        notebook: {
          label: '实验笔记',
          eyebrow: '代码',
          detail: '真实命令、源文件、指标和工件面板。',
        },
        research: {
          label: '研究',
          eyebrow: '来源',
          detail: '项目内部指南，以及实际查阅过的外部论文。',
        },
        audit: {
          label: '审计',
          eyebrow: '证据',
          detail: '时间线、关键记录文件，以及最终审计检查点。',
        },
      },
      evidenceLoaded: '已加载证据',
      guides: '指南',
      papers: '论文',
      oaPdfs: 'OA PDF',
      shellIntent: '界面意图',
      shellIntentBody: '这个界面应当像一个可检查的工作台：左侧是导航，中间是高密度证据区域，主内容窗格独立滚动。',
      openAccessResolved: (count: number) => `已解析 ${count} 个开放获取来源`,
      realEvidence: '真实本地笔记、工件与代码',
    },
    controls: {
      toggleTheme: '切换颜色主题',
      switchToDark: '切换到深色模式',
      switchToLight: '切换到浅色模式',
      darkMode: '深色模式',
      lightMode: '浅色模式',
      toggleLanguage: '切换语言',
      switchToChinese: '切换到简体中文',
      switchToEnglish: '切换到英文',
      english: 'English',
      chinese: '简体中文',
      englishShort: 'EN',
      chineseShort: '简中',
    },
    common: {
      open: '打开',
      hide: '收起',
      noEvidence: '当前没有可用的证据文件。',
      fileCount: (count: number) => `${count} 个文件`,
      layer: (index: number) => `第 ${index} 层`,
      sourceFile: (path: string) => `源文件：${path}`,
      source: (path: string) => `来源：${path}`,
      sample: (sampleId: string) => `样本：${sampleId}`,
      totalThickness: (value: string) => `总厚度：${value} nm`,
      verifiedTotalError: '验证总误差',
      commands: '命令',
      files: '文件',
      metrics: '指标',
      evidence: '证据',
      records: '记录',
      timeline: '时间线',
      currentStage: '当前阶段',
      selected: '已选中',
      openPanels: '已打开面板',
      notResolved: '未解析',
      unknown: '未知',
      yearUnknown: '年份未知',
      venueUnresolved: '期刊或会议未解析',
      currentSelectedStage: '当前所选阶段',
      reflectorAt: (material: string, value: string) => `${material} 反射层，厚度 ${value} nm`,
    },
    enums: {
      modelStatus: {
        baseline: '基线',
        retained: '已保留',
        competitive: '有竞争力',
        rejected: '已否决',
      },
      paperStatus: {
        downloaded: '本地 PDF 已就绪',
        'open-access-link': '仅有来源链接',
        'citation-only': '仅有引文',
      },
      paperCategory: {
        core: '核心论文',
        foundation: '方法基础',
        recent: '近期跟进',
      },
      panelKind: {
        artifact: '工件',
        code: '代码',
      },
      candidateFamily: {
        tandem: 'tandem',
        diffusion: 'diffusion',
        'continuous-cvae': 'continuous CVAE',
        'categorical-cvae': 'categorical CVAE',
      },
      candidateRoute: {
        shortlist: 'shortlist',
        'raw-best-of-64': 'raw best-of-64',
        'single-proposal': 'single proposal',
      },
    },
    home: {
      heroEyebrow: '不只看结论，要看完整故事',
      heroTitle: '沿着训练过程、含义解释和审计结论，理解为什么最后保留下来的是这条工作流。',
      walkPipeline: '查看流程',
      openNotebook: '打开实验笔记',
      compareModels: '比较模型',
      readResearch: '查看研究资料库',
      projectMode: '项目模式',
      projectModeTitle: '以证据为中心的工作台',
      projectModeDescription: '叙事、代码、论文和验证结果都被放进同一个应用框架里。',
      dataset: '数据集',
      datasetDescription: '这里展示的是真实光谱和真实 multilayer stack，而不是摘要占位信息。',
      research: '研究资料',
      researchDescription: '只有在来源合法允许的情况下，开放获取 PDF 才会保存在本地。',
      retainedWorkflow: '保留工作流',
      defaultPath: '默认路径',
      visualFirst: '先看可视化',
      visualTitle: '如果你想看仓库真正的“内部结构”，就去实验笔记页',
      visualDescription: '那一页会展示真实 CLI 入口、真实命令、真实指标文件，以及 Monaco 面板中的 shortlist 验证 JSON。',
      goToNotebook: '前往实验笔记',
      seePhysics: '查看 physics',
      seePhysicsTitle: '如果你想直接看真实光谱和层堆，就去 Explore',
      seePhysicsDescription: '在那里，数据集和候选结构不再只是名字，而会真正呈现为曲线、层结构和验证后的指标表。',
      openExplore: '打开 Explore',
      sourceTrail: '来源线索',
      sourceTrailTitle: '如果你想看笔记和书目，就去 Research',
      sourceTrailDescription: '指南解释了我们写了什么；论文库展示了我们实际查阅过的外部文献，并且只会在来源合法时显示本地开放获取 PDF。',
      openResearch: '打开 Research',
      sectionEyebrow: '这个应用能帮助你什么',
      sectionTitle: '一种更高信息密度的项目导航方式',
      sectionDescription: '目标是让项目变得可读，而不是把它压扁成营销页。每个部分都会回指真实的本地证据，同时用直白语言解释发生了什么。',
      chapter: (index: number) => `章节 ${index}`,
      twoReferenceWins: '两个参考目标的结果',
      whatHappenedOverTime: '时间线上发生了什么',
    },
    pipeline: {
      eyebrow: '流程与数据流',
      title: '这个项目是一连串决策，不是一个“点一下就出结果”的模型按钮',
      description: '这一节会展示每个阶段输入了什么、输出了什么，以及它为什么存在。最重要的观点是：最终答案来自一个闭环，而不是单次训练。先定义合法设计空间，再生成真实数据、训练快速近似器、采样候选，最后再回到 simulator 做最终检查。',
      designSpace: '设计空间',
      thicknessBounds: '厚度范围',
      thicknessDescription: '每一层 dielectric 都必须落在这个范围内。',
      spectralGrid: '光谱网格',
      spectralDescription: (start: string, stop: string) => `每条光谱覆盖 ${start} 到 ${stop} μm。`,
      keyBands: '关键波段',
      keyBandsDescription: 'solar band 和 8-13 μm atmospheric window 决定了这个项目的叙事重点。',
      visualStageMap: '阶段示意图',
      visualTitle: '把每个阶段都做成可检查的盒子后，这条流程就更容易理解了',
      visualDescription: '这些阶段与实验笔记页中的内容完全对应；在那里，每个阶段都能展开成 Monaco 代码面板、真实命令和工件输出。',
      openNotebook: '打开实验笔记',
      inputs: '输入',
      outputs: '输出',
      glossary: '白话术语表',
      loopMatters: '为什么这个闭环很重要',
      loopTitle: '训练结果从来没有被直接当成最终真相。',
      loopDescription: '这个项目最强的想法并不在“装饰感”，而在步骤本身：先广泛采样、快速评分，再回到 simulator 后才宣布某个设计是好的。因此，最终结果比单个模型指标更可信。',
      stepLabel: (index: number, eyebrow: string) => `${index}. ${eyebrow}`,
    },
    compare: {
      eyebrow: '模型比较',
      title: '赢下来的工作流，靠的是验证，而不是自信',
      description: '这一页关注的是：当每个模型家族都被送进同一条证据闭环后，它们究竟表现如何。指标当然重要，但真正决定胜负的是 shortlist 和 simulator 检查之后的 verified target error。',
      retainedBestMethod: '保留的最佳方法',
      inspectNotebook: '检查运行笔记',
      seeWinningStructures: '查看获胜结构',
      split: '划分方式',
      device: '设备',
      verifiedHighlights: '验证亮点',
      targetTitle: '这个目标上发生了什么',
    },
    explore: {
      eyebrow: '数据与候选探索器',
      title: '真实光谱与真实验证后的层堆',
      description: '这个视图把两类证据分开了。第一类是 4096 条训练语料中的真实样本，你可以直接看它们的光谱。第二类是从模型比较故事中筛出来的、经过验证的候选结构。',
      datasetSamplePicker: '真实数据集样本选择器',
      candidatePicker: '已验证候选选择器',
      realSpectrumViewer: '真实光谱查看器',
      verifiedCandidate: '已验证候选',
      targetMetrics: '目标指标',
      simulatorMetrics: 'simulator 确认后的指标',
      absoluteError: '按指标拆分的绝对误差',
      reflectance: 'Reflectance',
      emissivity: 'Emissivity',
    },
    notebook: {
      eyebrow: '实验笔记',
      title: '故事背后真实的代码、命令和工件文件',
      stageCount: (count: number) => `${count} 个笔记阶段`,
      commandCount: (count: number) => `${count} 条真实命令`,
      panelCount: (count: number) => `${count} 个代码与工件面板`,
      currentStageBadge: (eyebrow: string) => `当前阶段：${eyebrow}`,
      stageCardDescription: '从 config 和数据集生成，一直到 shortlist 验证和最终审计。',
      commandCardDescription: '当前仓库使用过的复现实验命令与命令模式。',
      panelCardDescription: 'Monaco 标签页允许你直接检查源文件、指标包和验证 JSON。',
      workspaceTabs: {
        files: '代码与工件',
        commands: '终端命令',
        overview: '阶段笔记',
      },
      noPanels: '这个阶段当前没有可展示的代码或工件面板。',
      whatHappenedHere: '这里发生了什么',
      whyItMatters: '为什么它重要',
    },
    research: {
      eyebrow: '研究资料库',
      title: '一边是内部指南，一边是真正查阅过的外部论文',
      description: '这一页把两类证据明确分开了。Guides 是我们为这个项目写的本地 markdown 笔记；papers 是我们实际查阅过的外部来源，并且只有在能解析到合法 OA 副本时，才会提供官方链接或本地开放获取 PDF。',
      internalGuides: '内部指南',
      papersReviewed: '已审阅论文',
      localPdfs: '本地 OA PDF',
      resolvedLinks: '已解析 OA 链接',
      internalGuidesDescription: '在这个项目过程中写下来的本地 markdown 讲解与审计文档。',
      papersDescription: '根据本地书目和文献笔记解析出来的论文列表。',
      localPdfsDescription: '只有在能发现官方开放获取 PDF 时才会下载。',
      resolvedLinksDescription: 'OpenAlex 成功解析出开放获取来源 URL 的参考文献数量。',
      searchLabel: '在指南和论文中搜索',
      searchPlaceholder: "可以试试 'diffusion'、'Bayesian' 或 'Keawmuang'",
      paperLibrary: '论文库',
      guideLibrary: '指南库',
      paperVisibleCount: (visible: number, total: number) => `当前显示 ${visible} / ${total} 篇论文。`,
      guideVisibleCount: (visible: number, total: number) => `当前显示 ${visible} / ${total} 份指南。`,
      guideShelf: '指南书架',
      paperShelf: '论文书架',
      internalProjectGuide: '内部项目指南',
      authors: '作者',
      venue: '期刊或会议',
      year: '年份',
      citations: '引用量',
      overview: '概览',
      details: '详情',
      pdf: 'PDF',
      openOfficialSource: '打开官方来源',
      openLocalPdf: '打开本地 PDF',
      localPdfSize: (size: string) => `本地 PDF 大小：${size}`,
      externalPdfFound: '已经找到开放获取来源 URL，但没有下载本地 PDF。',
      noLocalPdf: '当前工作区中没有这条参考文献的本地 PDF。',
      embeddedLocalPdf: '嵌入式本地 PDF',
      embeddedPdfNote: 'PDF 会保持在视图中，同时书架与元数据保持固定。',
      standaloneView: '独立查看',
      browserDidNotRender: '浏览器没有成功内嵌渲染这个 PDF。',
      openPdfNewTab: '在新标签页中打开本地 PDF',
      referenceDetails: '参考文献信息',
      doi: 'DOI',
      officialLink: '官方链接',
      openAccessPdfUrl: '开放获取 PDF URL',
      projectNote: '项目说明',
      availability: '可用性',
      availabilityLocal: '工作区中存在本地 PDF，可以在 PDF 标签页中直接打开。',
      availabilityExternal: '外部 PDF 链接已经解析到，但生成器没有保存本地副本。',
      availabilityNone: '当前只有引文和官方来源可用。',
      sourceNote: '来源说明',
      whyPaperMattered: '这篇论文为什么对项目重要',
      pdfAvailabilityRule: 'PDF 可用性规则',
      pdfAvailabilityRuleBody: '只有在能解析到官方开放获取 PDF URL 时，应用才会保存本地 PDF。如果论文不是开放获取，应用只保留引文与官方来源链接，不会重新托管论文本体。',
      noGuides: '当前搜索条件下没有匹配的指南。',
      noPapers: '当前搜索条件下没有匹配的论文。',
    },
    audit: {
      eyebrow: '最终审计',
      title: '最终结果之所以保守，是因为证据本身也保持保守',
      description: '审计不只是一次总结，它检查了数据集、训练环境以及最可能残留的建模问题。最终结论是保留 continuous-CVAE shortlist 工作流，因为经过审计的 categorical 分支在完整验证下仍然没有赢过它。',
      checkpointCount: (count: number) => `${count} 个审计检查点`,
      recordCount: (count: number) => `${count} 份关键记录文件`,
      selectedCheckpointBadge: (title: string) => `当前检查点：${title}`,
      auditVerdict: '审计结论',
      auditVerdictTitle: '把 continuous-decoder CVAE 保留为默认方案。',
      auditVerdictDescription: 'categorical-material decoder 的确回应了一个真实的建模失配问题，但在走完同样的 shortlist + physics 闭环后，它仍然没有超过保留工作流。',
      auditTimeline: '审计时间线',
      selectedCheckpoint: '当前检查点',
      workspaceTabs: {
        evidence: '检查点证据',
        records: '关键记录文件',
        verdict: '审计结论',
      },
      checkpoint: (index: number) => `检查点 ${index}`,
      verdict: '结论',
      checkpointSummaries: '检查点摘要',
      datasetSize: '数据集规模',
      datasetSizeDetail: '最终训练语料中的真实 WPTherml 记录数。',
      wavelengthGrid: '波长网格',
      wavelengthGridDetail: '每条 reflectance 与 emissivity 光谱都使用这么多个真实波长点。',
      retainedWinner: '保留优胜者',
      retainedWinnerDetail: '最终报告中展示的最佳精选验证误差。',
      categoricalBranch: 'Categorical 分支',
      categoricalBranchDetail: '被否决的 categorical 审计分支在 sample255 上的原始误差。',
    },
  },
} as const

export type Copy = (typeof copy)[keyof typeof copy]
